# -*- coding: utf-8 -*-
"""Batch Mode code for minor project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iaz1h0cfZhs2c_c5-L_KZuS2p8HKG7H3
"""

import re

def validate_email(email):
    pattern = r'^[a-zA-Z0-9!#$%&\'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&\'*+/=?^_`{|}~-]+)*@[a-zA-Z0-9-]+(?:\.[a-zA-Z]{2,})+$'
    return re.match(pattern, email) and len(email) <= 254
batch_email = "example@example.com"
if validate_email(batch_email):
    print(f"{batch_email} is a valid email address.")
else:
    print(f"{batch_email} is not a valid email address.")