# -*- coding: utf-8 -*-
"""Interactive mode code for Minor Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hsh4QpR9h2DFIzX0SpK84b6MR3-fHvQM
"""

import re
def validate_email(email):
    pattern = r'^[a-zA-Z0-9!#$%&\'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&\'*+/=?^_`{|}~-]+)*@[a-zA-Z0-9-]+(?:\.[a-zA-Z]{2,})+$'
    return re.match(pattern, email) and len(email) <= 254
user_email = input("Enter an email address: ")
if validate_email(user_email):
    print(f"{user_email} is a valid email address.")
else:
    print(f"{user_email} is not a valid email address.")