# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BDzkI1gRwh7EqY3vp2duxyttBkTyTKUv
"""

import re

def validate_email(email):
    # Define the regular expression pattern for a valid email address
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

    # Use re.match() to check if the email matches the pattern
    if re.match(pattern, email):
        print(f"{email} is a valid email address.")
    else:
        print(f"{email} is not a valid email address.")

# Get user input for email address
user_email = input("Enter an email address: ")

# Validate the email address
validate_email(user_email)